# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
 
 

- task: ArchiveFiles@2
  inputs:
      rootFolderOrFile: './SiteServicesBot'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: './SiteServicesBot.zip'
      replaceExistingArchive: true
  
- task: LambdaDeployFunction@1   
  inputs:
    awsCredentials: 'OperationsLambdaDeployments'
    regionName: 'us-east-1'
    deploymentMode: 'codeonly'
    functionName: 'SiteServicesBot'
    codeLocation: 'localfile'
    localZipFile: './SiteServicesBot.zip'
    outputVariable: 'outputvar'
    logRequest: true
    logResponse: true 